@startuml Payments
autonumber

actor Prepayer

Prepayer -> ReferralGateway: prePayment(contribution, tDaoName, parent)

alt contribution is in range

    alt preJoinEnabled == true

        alt Is not member

            alt referralDiscount == true
                ReferralGateway --> ReferralGateway: increase Referral Reserve
                
                alt valid parent
                    ReferralGateway --> ReferralGateway: apply referral discount
                    ReferralGateway --> ReferralGateway: calculate parent reward
                end

            ReferralGateway --> ReferralGateway: apply prejoin discount
            ReferralGateway --> ReferralGateway: create new member
            ReferralGateway --> ReferralGateway: update repool balance
            ReferralGateway --> ReferralGateway: update DAO variables
            Prepayer --> ReferralGateway: Transfer Contribution
            ReferralGateway --> Operator: Transfer Fee
            ReferralGateway --> BMOracle: Request BM
            ReferralGateway --> Prepayer: Emit OnPrepayment event
            end

        else Is member
            ReferralGateway --> Prepayer: Revert
        end

    else preJoinEnabled == false
    ReferralGateway -> DAO: joinPool(WIP)
    end

else contribution is out of range
    ReferralGateway --> Prepayer: Revert
end

@enduml    
