@startuml Launch activation
autonumber

actor Deployer
actor DaoAdmin

Deployer -> DAO: Deploy
DaoAdmin -> ReferralGateway: launcDAO(DAOName, DAOAddress, isReferralDiscountEbnabled)

alt Valid admin and DAO
    ReferralGateway --> ReferralGateway: Set DAO variables
    ReferralGateway --> ReferralGateway: Disable prejoin

else Invalid admin or DAO
    ReferralGateway -> DaoAdmin: Revert
end

@enduml    
