@startuml Join Dao
autonumber

actor User

User -> ReferralGateway: joinDao(newMember)

alt if dao is address zero
    ReferralGateway --> User: Revert

else dao address is valid

    alt if newMember is not KYC
        ReferralGateway --> User: Revert

    else newMember is KYC

        alt isPreJoinEnabled == false
            ReferralGateway --> User: Revert

        else isPreJoinEnabled == true

            alt if newMember has a parent
                ReferralGateway -> Parent: Transfer reward
                ReferralGateway --> ReferralGateway: Parent reward for child is set to 0
                ReferralGateway -> ReferralGateway: Emit event OnParentRewarded(parent, child, reward) 
            end

            ReferralGateway --> TDao: joinByReferral(newMember, contribution)
            TDao -> TDao: Create Member
            TDao -> TDao: Run all fud algorithms
            ReferralGateway -> TDao: Transfer contribution
            
        end
    end
end

@enduml    
