@startuml Launch activation
autonumber

actor Deployer
actor Parents
actor DaoAdmin

Deployer -> ReferralGateway: Deploy
Parents -> ReferralGateway: Register
DaoAdmin -> ReferralGateway: createDao

ref over ReferralGateway
    Prepayments -> referral-prepayments
    KYC -> set-kyc
end ref

Deployer -> TheLifeDao: Deploy

ref over ReferralGateway
    Prepayers join dao -> join-dao
end ref

ReferralGateway -> TheLifeDao: create members

@enduml    
