@startuml Referrals and Prepayments
autonumber

actor Prepayer

Prepayer -> ReferralGateway: prePayment(parent, contribution, tDaoName)

alt isPreJoinEnabled == false
    ReferralGateway --> Prepayer: Revert

else isPreJoinEnabled == true

    alt contribution is out of range
        ReferralGateway --> Prepayer: Revert

    else contribution amount is valid
        ReferralGateway -> ReferralGateway: Create PrePaidMember(tDaoName, child, parent, contribution)
        Prepayer -> ReferralGateway: Transfer contribution

        loop up to 4 levels
            ReferralGateway --> ReferralGateway: Calculate the reward based on layer
                    
            alt current child is kyc
                ReferralGateway -> Parent: Transfer reward
                ReferralGateway --> ReferralGateway: Parent reward for child is set to 0
                ReferralGateway -> ReferralGateway: Emit event OnParentRewarded(parent, caller, reward)
                    
            else current child is not kyc
                ReferralGateway --> ReferralGateway: Parent reward set to reward                   
            end

        break When parent == address(0)
        end
    end
        
        ReferralGateway -> ReferralGateway: Update collected fees, and dao metrics
        ReferralGateway -> ReferralGateway: Emit event OnPrePayment(parent, child, contribution)
    end
end

@enduml    
