@startuml Referrals and Prepayments
autonumber

actor Prepayer

Prepayer -> ReferralGateway: prePayment(parent, contribution, tDaoName)

alt isPreJoinEnabled == false
    ReferralGateway --> Prepayer: Revert

else isPreJoinEnabled == true

    alt contribution is out of range
        ReferralGateway --> Prepayer: Revert

    else contribution amount is valid
        ReferralGateway -> ReferralGateway: Create PrePaidMember(contribution, tDaoName, parent)
        Prepayer -> ReferralGateway: Transfer contribution

        loop up to 4 levels
            alt parent != address(0) &&  parent is KYC
                ReferralGateway --> ReferralGateway: Calculate the reward based on layer
                ReferralGateway --> ReferralGateway: Parent reward set to reward                   
                                
            end

        break When parent == address(0) or parent is not KYC
        end
    end
        
        ReferralGateway -> ReferralGateway: Update collected fees, and dao metrics
        ReferralGateway -> ReferralGateway: Emit event OnPrePayment(parent, child, contribution)
    end
end

@enduml    
