@startuml Referrals and Prepayments
autonumber

actor Prepayer

Prepayer -> ReferralGateway: prePayment(parent, contribution, tDaoName)

alt if pre join is disabled
    ReferralGateway --> Prepayer: Revert
else 
    alt if contribution is out of range
        ReferralGateway --> Prepayer: Revert
    else
        ReferralGateway -> ReferralGateway: Create PrePaidMember(tDaoName, child, parent, contribution)
        Prepayer -> ReferralGateway: Transfer contribution
        alt if parent != address(0)
            loop until parent is address(0) or up to 4 levels
                alt if the current child has a parent
                    ReferralGateway --> ReferralGateway: Calculate the reward based on layer
                    alt if the current child is kyc
                        ReferralGateway -> Parent: Transfer reward
                        ReferralGateway --> ReferralGateway: Parent reward for child is set to 0
                        ReferralGateway -> ReferralGateway: Emit event OnParentRewarded(parent, caller, reward)
                    else
                        ReferralGateway --> ReferralGateway: Parent reward set to reward                   
                    end
                else
                    ReferralGateway --> ReferralGateway: Break loop
                end
            end
        end
        ReferralGateway -> ReferralGateway: Update collected fees, and dao metrics
        ReferralGateway -> ReferralGateway: Emit event OnPrePayment(parent, child, contribution)
    end
end

@enduml    
