@startuml Set KYC
autonumber

actor Backend

Backend -> ReferralGateway: setKYCStatus(child)

alt if child is address zero
    ReferralGateway --> Backend: Revert
else 
    alt if child is already KYC
        ReferralGateway --> Backend: Revert    
    else
        ReferralGateway -> ReferralGateway: Set KYC status to true
        alt if child has already prepaid and has a parent
            ReferralGateway -> Parent: Transfer reward
            ReferralGateway --> ReferralGateway: Parent reward for child is set to 0
            ReferralGateway -> ReferralGateway: Emit event OnParentRewarded(parent, child, reward) 
        end
        ReferralGateway -> ReferralGateway: Emit event OnChildKycVerified(child)        
    end    
end

@enduml    
