@startuml Set KYC
autonumber

actor Backend

Backend -> PrejoinModule: setKYCStatus(user)

alt Module is enabled
    alt Member address is valid
        alt Member is not KYC verified
            alt Member has paid contribution

                PrejoinModule -> PrejoinModule: Set KYC status to true
        
                loop for each valid parent up until 4 layers
                    PrejoinModule --> Parent: Transfer reward
                end

                PrejoinModule --> Backend: Emit OnParentReward event 

            else Member has not paid contribution
                PrejoinModule --> Backend: Revert
            end

        else Member is KYC verified
            PrejoinModule --> Backend: Revert            
        end    
    
    else member address is invalid
      PrejoinModule --> Backend: Revert    
    end

else Module is disabled
    PrejoinModule --> Backend: Revert
end

@enduml    
