@startuml Set KYC
autonumber

actor Backend

Backend -> ReferralGateway: setKYCStatus(member, tDAOName)

alt member address is valid

    alt Member is not KYC verified

        alt Member has paid contribution

            ReferralGateway -> ReferralGateway: Set KYC status to true
        
        loop for each valid parent up until 4 layers
            ReferralGateway --> Parent: Transfer reward
        end

        ReferralGateway --> Backend: Emit OnParentReward event 

        else Member has not paid contribution
            ReferralGateway --> Backend: Revert
        end

    else Member is KYC verified
        ReferralGateway --> Backend: Revert            
    end    
    
else member address is invalid
    ReferralGateway --> Backend: Revert    
end

@enduml    
