@startuml Subscription and Refund
title Subscription and refund
autonumber

actor Backend
actor User
participant SubscriptionModule
participant MembersData
participant KYCModule
participant CouponPool
participant RewardsModule

Backend -> SubscriptionModule: paySubscriptionOnBehalfOf(memberWallet, parentWallet, contribution)

break [Caller-NOT-valid]
  SubscriptionModule -x Backend: revert InvalidCaller()
end

break [Module-disabled]
  SubscriptionModule -x Backend: revert ModuleDisabled()
end

break [Contribution-less-than-25-USDC]
  SubscriptionModule -x Backend: revert WrongContribution()
end

SubscriptionModule -> MembersData: getAssociationMemberData(memberWallet)
MembersData --> SubscriptionModule: Member data

break [Member-invalid]
  SubscriptionModule -x Backend: revert InvalidMember()
end

opt [Parent-wallet-not-zero]
  SubscriptionModule -> MembersData: getAssociationMemberData(parentWallet)
  MembersData --> SubscriptionModule: Parent data

  break [Parent-invalid]
    SubscriptionModule -x Backend: revert InvalidParent()
  end

  SubscriptionModule -> RewardsModule: assignParentReward
end

SubscriptionModule -> MembersData: registerAssociationMember(memberWallet, parentWallet, contribution)
MembersData -> MembersData: Emits event
MembersData --> SubscriptionModule: success

CouponPool -> SubscriptionModule: transfer contribution

opt [KYC-user]
  SubscriptionModule -> KYCModule: approveKYC(memberWallet)
  KYCModule -> KYCModule: Emits event
end

opt [<30-days-and-no-service]
  User -> Backend: request refund
  Backend -> SubscriptionModule: refund(memberWallet)
  SubscriptionModule -> MembersData: getAssociationMemberData(memberWallet)
  MembersData --> SubscriptionModule: Member data

  break [Member-invalid]
    SubscriptionModule -x Backend: revert InvalidMember()
  end

  SubscriptionModule -> CouponPool: transfer contribution back
  SubscriptionModule -> MembersData: updateAssociationMember(memberWallet)
  MembersData -> MembersData: Emits event
  SubscriptionModule -> SubscriptionModule: Emits event
  CouponPool --> User: transfer contribution back

  opt [there-was-a-parent]
    SubscriptionModule -> RewardsModule: revokeParentReward
    RewardsModule -> RewardsModule: Emits event
  end
end

@enduml
