@startuml Subscriptions_without_benefits
title Subscription without benefits
autonumber

!include subscription-common.puml

actor Backend
actor Parent
participant SubscriptionModule
participant KYCModule
participant MembersData
participant RewardsModule
participant CouponPool
participant Reserve

Backend -> SubscriptionModule: paySubscriptionOnBehalfOf(memberWallet, parentWallet, contribution)

PRECHECKS_CALLER_MODULE()
PRECHECKS_CONTRIB_MIN25()
LOAD_MEMBER_AND_VALIDATE()
OPTIONAL_PARENT_VALIDATE()

' Asignar reward si hubo parent
opt [there-was-a-parent]
  SubscriptionModule -> RewardsModule: assignParentReward
end

REGISTER_AND_CONFIRM()

CouponPool -> SubscriptionModule: transfer contribution
KYC_OPT()

opt [>30-days-passed-or-apply-to-service]
  SubscriptionModule -> Reserve: transfer contribution to Reserve
  Reserve -> Reserve: Run algorithms (Do not include member)

  opt [there-was-a-parent]
    SubscriptionModule -> RewardsModule: rewardParent
    RewardsModule -> RewardsModule: Emits event
    RewardsModule --> Parent: transfer parent reward
  end
end

@enduml
