@startuml High Level Modular Architecture

!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Container.puml

AddRelTag("sync", $textColor="black", $lineColor="black", $lineStyle = DashedLine())

LAYOUT_WITH_LEGEND()

Person(user, "User")

System(takasureReserve, "TakasureReserve") {
    Container(reserveLogic, "Reserve Logic")
    Container(reserveState, "Reserve State")
}

System(router, "Router"){
    Container(routerLogic, "Router Logic")
}

System(modulesManager,"Modules Manager"){
    Container(managerLogic, "Manager Logic")
    Container(managerState, "Manager State")
}

System(modules,"Modules"){
    Container(modulesLogic, "Modules Logic")
    Container(modulesState, "Modules State")
}

System(hooks, "Hooks") {
    Container(hooksLogic, "Hooks Logic")
}

System(utils, "Utils") {
    Container(helpers, "Helpers")
}

System_Ext(prejoinModule,"Prejoin Module", "Manages prejoins")
System_Ext(entryModule,"Entry Module", "Manages joins")
System_Ext(memberModule,"Member Module", "Manages members")
System_Ext(revenueModule,"Revenue Module", "Manages external revenue")

Rel_D(user, routerLogic, "Call", $tags="sync")
Rel_D(user, modulesLogic, "Call", $tags="sync")
Rel_D(router, modules, "Route", $tags="sync")
Rel_D(modulesLogic, prejoinModule, "", $tags="sync")
Rel_D(modulesLogic, entryModule, "", $tags="sync")
Rel_D(modulesLogic, memberModule, "", $tags="sync")
Rel_D(modulesLogic, revenueModule, "", $tags="sync")
Rel_D(reserveLogic, managerLogic, "Module exists", $tags="sync")
Rel_D(modulesLogic, hooks, "Ask and send state", $tags="sync")
Rel_D(hooksLogic, reserveState, "Get and set state", $tags="sync")
Rel_L(modules, reserveState, "Execute", $tags="sync")
Rel_D(modulesLogic, utils, "Use", $tags="sync")

@enduml