name: Run Tests on PR Creation

on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: "nightly"

      - name: Install dependencies
        run: yarn install

      - name: Clear cache
        env:
          ARBITRUM_MAINNET_RPC_URL: ${{ secrets.ARBITRUM_MAINNET_RPC_URL}}
          TESTNET_DEPLOYER_PK: ${{secrets.TESTNET_DEPLOYER_PK}}
        run: yarn hardhat clean --config hardhat-continuous-integration.config.js

      - name: Compile contracts
        env:
          ARBITRUM_MAINNET_RPC_URL: ${{ secrets.ARBITRUM_MAINNET_RPC_URL}}
          TESTNET_DEPLOYER_PK: ${{secrets.TESTNET_DEPLOYER_PK}}
        run: yarn hardhat compile --config hardhat-continuous-integration.config.js
        id: hardhat-compile

      - name: Forge Build
        run: |
          forge --version
          forge build --sizes
        id: forge-build  

      - name: Hardhat test
        env:
          ARBITRUM_MAINNET_RPC_URL: ${{ secrets.ARBITRUM_MAINNET_RPC_URL }}
          TESTNET_DEPLOYER_PK: ${{ secrets.TESTNET_DEPLOYER_PK }}
        run: yarn test --config hardhat-continuous-integration.config.js

      - name: Forge Test
        run: |
          forge test -vvv